### ISSUE TITLE
Missing calledBefore/After

### ISSUE THREAD

**Issue by NemoStein** [shouldjs/sinon#10]
Missing the `calledBefore` and `calledAfter` methods.
E.g.: `spy.should.be.calledBefore(anotherSpy)`

**Comment by btd** [comment]
This module is a thin wrapper around sinonjs own assertions. If sinonjs will add this methods i will add them also.
You can take a look to should-spies, it is just bare bone spy and i am more liberal about adding methods to it.

**Comment by NemoStein** [comment]
I don't think I understood you right...
> If sinonjs will add this methods i will add them also.

In fact, [Sinon do have this methods](http://sinonjs.org/docs/#spies-api)!

**Comment by btd** [comment]
You are looking to spy api. But i am talking about assertion api.

**Comment by NemoStein** [comment]
WOW! Now I get it...
I just looked into shouldjs/spies and it doesn't have those methods too (as I presumed from your "*i am more liberal about adding methods to it*" comment)...
Would you add them?

**Comment by btd** [comment]
@NemoStein added
