### ISSUE TITLE
Unhelpful AssertionError message when .not is used with .called (and possibly others)

### ISSUE THREAD

**Issue by NemoStein** [shouldjs/sinon#5]
Consider the following test:

    it('should not call the spy', function() {
        var spy = sinon.spy();
        spy();
        spy.should.not.be.called();
    });

This test throws this really messed up message:

    AssertionError: expected 'spy' not to have been called at least once but was never called (false negative fail)

This message gave me a headache trying to understand what was wrong.
This is what I expected from the assertion (or something along this):

    AssertionError: expected 'spy' not to have been called but was called X times

**Comment by btd** [comment]
Hi, sorry for late response.
How it can be called X times if it was never called? I think better message would be just:
```
expected 'spy' not to have been called (false negative fail)
```
Parts: `expected 'spy'` and `(false negative fail)` - non removable.

**Comment by NemoStein** [comment]
You see, there is the problem...

> How it can be called X times if it was never called?

The spy was, indeed, **called** once, but was expected to not be called (check my unit test example again), and the message is heavily misleading.

**Comment by btd** [comment]
Ahh, got it now.

**Comment by btd** [comment]
I changed message to be:
```
expected 'spy' not to have been called, but was called once (false negative fail)
```
Thanks.

**Comment by NemoStein** [comment]
https://github.com/shouldjs/sinon/commit/1b9848cafda3fccbe3e72d7e89db1684d7f68186 - Purrfect!
