### ISSUE TITLE
isSinonStub is not defined

### ISSUE THREAD

**Issue by lbeschastny** [shouldjs/sinon#6]
You have an undefined `isSinonStub` function here:
https://github.com/shouldjs/sinon/blob/master/should-sinon.js#L29

I've just stumbled on it trying to use `should-sinon` sugar with a [`spyCall` object][1].

  [1]: http://sinonjs.org/docs/#spycall

**Comment by btd** [comment]
I just published 0.0.4. Could you give it a try pls?

**Comment by lbeschastny** [comment]
@btd everything works like a charm now, thanks!

**Comment by btd** [comment]
:+1:
