### ISSUE TITLE
API unclear - more documentation needed?

### ISSUE THREAD

**Issue by ErisDS** [shouldjs/sinon#8]
I've been trying to use this library to improve assertions

 E.g. changing

`someStub.calledTwice().should.be.true()` to `someStub.should.be.calledTwice()` 

Seems to work, however if I change

`someStub.calledWith(something).should.be.true()`

to 

`someStub.should.be.calledWith(something)`

The latter form always returns true as far as I can tell.

There is very minimal documentation, so I can't tell if this is a bug or if I'm using the library wrong. 

I've also had difficulties with getters (although these only have minimal support in sinon) and with any stub that was set using [rewire](https://github.com/jhnns/rewire). 

It would be really helpful to get some more documentation for this module so that it's easier to reason about these cases and why they don't work.

**Comment by btd** [comment]
For me .calledWith works fine:
```
> var should = require('should')
> require('.')
> var sinon = require('sinon')
> var spy = sinon.spy();
> spy(1, 2, 3)
> spy.should.be.calledWith(1, 2, 3)
Assertion { ... }
> spy.should.be.calledWith(1, 2, 2)
AssertionError: expected 'spy' to be called with arguments 1, 2, 2
    spy(1, 2, 3) at repl:1:1
    expected false to be true
...
```
Can you provide failing example?

Also i agree about not clear docs, i just do not have enough time to keep docs up to date. You can just take as a rule that everything provided by should-sinon is just all sinon ows assertions. Also there is no getters, everything is function call.

**Comment by ErisDS** [comment]
Sorry - I moved away from using the module because it produced false positives for me. I was trying to use both this module + stubs for getters at the same time & the result was very very confusing.

Chances are that the problem is more along the lines that this module doesn't work with getters (sinon itself only *just* works with them).

**Comment by btd** [comment]
Do you have some small reproducible example, that i can use as starting point for improvement. I would be greatly appriciated. For now this is only small wrapper around sinon own assertions. But i think i will need to use should own internals to do more accurate assertions.
